CHLA_ERROR_ESTIMATION <- function (filenc,CHLA_ADJUSTED,ERROR) {

#PRES=ncvar_get(filenc,"PRES")

CHLA_ADJUSTED_ERROR=ncvar_get(filenc,"CHLA_ADJUSTED_ERROR")

ERROR_TEMP=abs(ERROR*CHLA_ADJUSTED)+0.02

ERROR_TEMP[which(ERROR_TEMP<0.02)]=0.02

CHLA_ADJUSTED_ERROR=ERROR_TEMP

return(CHLA_ADJUSTED_ERROR)

}
